steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/headless-utils/resume-api', '.']
  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/headless-utils/resume-api']
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'resume-api'
      - '--image'
      - 'gcr.io/headless-utils/resume-api'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'TOGETHER_API_KEY=492d06035d1fb29fc36b26ba45d4746734b41f077027213f2b73bf7bee5a64d3,DATABASE_URL=postgresql://neondb_owner:u0mveDWql9gx@ep-proud-glitter-a5blpm24-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--port'
      - '8080'
      - '--timeout'
      - '180'  # 5 minutes timeout
