steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/headless-utils/resume-frontend-chits', '.']
    env:
      - 'VITE_DATABASE_URL=${_VITE_DATABASE_URL}'
  
  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/headless-utils/resume-frontend-chits']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'chat-ui'
      - '--image'
      - 'gcr.io/headless-utils/resume-frontend-chits'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--set-env-vars'
      - 'VITE_DATABASE_URL=${_VITE_DATABASE_URL}'

substitutions:
  _VITE_DATABASE_URL: ${VITE_DATABASE_URL} # Replace with the actual value
images:
  - 'gcr.io/headless-utils/resume-frontend-chits'